Create endpoint for product page
TaranBohdan/shop pull request #21
Opened 2024-04-02 05:37 UTC by TaranBohdan

2024-04-02 06:03 UTC, obaibula requested changes

2024-04-02 06:03 UTC, obaibula commented on src/main/java/com/stamp/shop/product/entity/ProductDTO.java
> +    private ProductDescription productDescription;
Create a separate record, and name it ProductDescriptionDTO. Don't mess entites and embeddables with dtos.

2024-04-02 06:03 UTC, obaibula commented on src/main/java/com/stamp/shop/product/entity/ProductDTO.java
> +package com.stamp.shop.product.entity;
move to product.dto package

2024-04-02 07:21 UTC, TaranBohdan commented on src/main/java/com/stamp/shop/product/entity/ProductDTO.java
> +public class ProductDTO {
I made it as record, but I could not use it in Tests

2024-04-04 06:05 UTC, obaibula approved these changes
Fix comments before merge

2024-04-04 06:05 UTC, obaibula commented on src/main/java/com/stamp/shop/product/ProductService.java
> +                        "Product with id %s was not found", id
Also it should be "%d" instead of "%s", because Long id is not String.

2024-04-04 20:30 UTC, merged